# Header
menu:
  HOMEPAGE: /
  NEWS: /news
  DOCS: /docs
  MEMBERS: /members
  ABOUT: /about
  CONTACT: /contact

# Content
excerpt_link: Read more

# Toc
toc: true

# MIIT ICP/IP/DOMAIN
beian: 
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Miscellaneous
favicon: /favicon.ico
webclip: /images/webclip
brand:   /images/brand.svg

# Jumbotron video & Hero image
## Jumbotron video
video: 
  overlay: true
  path: /images/
## Hero image
hero: 
  image: /images/banner.jpg
## keen-slider
keen_slider: 
  enable: false

# Slogan
slogan: 
  primary: We look at the same sky, the same star, a shared destiny.
  secondary: We are <b>FRC Zodiac 6353</b> from <b>No. 2 High School of East China Normal University</b> in Shanghai, China.
  archives: 汇聚热点话题 打造创新思路
  pages: Welcome to Zodiac6353!
  posts: 实践见真知既是最好的解释

