- name: What is FRC?
  en_name: FRC (FIRST® Robotics Competition)
  description: The goal of FIRST® is to inspire young people to be science and technology leaders and innovators by engaging them in exciting mentor-based programs. FIRST® holds annual robotics competitions where teams are required to build robots to compete with each other.
  cover: /images/album/frc.jpg
  # link: "https://www.firstinspires.org/"
  # preview: FRC Official Site